fos_elastica:
    clients:
        default:
          host: localhost
          port: 9200
    indexes:
        app:
           index_name: blog
            
           settings: 
              analysis: 
                 filter: 
                    nGram_filter: 
                       type: nGram
                       min_gram: 2
                       max_gram: 20
                       token_chars: [letter,digit,punctuation,symbol]

                    english_stop:
                       type:       stop
                       stopwords:  _english_

                    english_stemmer:
                      type:       stemmer
                      language:   english

                    english_possessive_stemmer:
                      type:       stemmer
                      language:   possessive_english

                 analyzer:
                    store_analyzer:
                       type: custom
                       tokenizer: whitespace
                       filter: [english_possessive_stemmer,lowercase,asciifolding,english_stop,english_stemmer,nGram_filter]

                    search_analyzer:
                       type: custom
                       tokenizer: whitespace
                       filter: [english_possessive_stemmer,lowercase,asciifolding,english_stop,english_stemmer]
              
           types:
              post:

                  mappings:
                      id: ~
                      title:
                        type: string
                        index_analyzer: store_analyzer
                        search_analyzer: search_analyzer
                      summary: ~

                  persistence:
                      driver: orm
                      model: AppBundle\Entity\Post
                      provider: ~
                      listener: ~
                      finder: ~